export enum ArtifactDEMType {
  MODEL = 'MODEL',
  METADATA = 'METADATA',
  ROI = 'ROI',
  LEGEND = 'LEGEND',
}

export enum ArtifactRasterType {
  //** test */
  GPKG = 'GPKG',
  LEGEND = 'LEGEND',
  METADATA = 'METADATA',
  THUMBNAILS_SMALL = 'THUMBNAILS_SMALL',
  THUMBNAILS_MEDIUM = 'THUMBNAILS_MEDIUM',
  THUMBNAILS_LARGE = 'THUMBNAILS_LARGE',
}

export enum Artifact3DType {
  MODEL_3D = 'MODEL_3D',
  METADATA = 'METADATA',
  THUMBNAILS_SMALL = 'THUMBNAILS_SMALL',
  THUMBNAILS_MEDIUM = 'THUMBNAILS_MEDIUM',
  THUMBNAILS_LARGE = 'THUMBNAILS_LARGE',
}
