export enum ProductType {
  ORTHOPHOTO = 'Orthophoto',
  ORTHOPHOTO_HISTORY = 'OrthophotoHistory',
  ORTHOPHOTO_BEST = 'OrthophotoBest',
  RASTER_MAP = 'RasterMap',
  RASTER_MAP_BEST = 'RasterMapBest',
  RASTER_AID = 'RasterAid',
  RASTER_AID_BEST = 'RasterAidBest',
  RASTER_VECTOR = 'RasterVector',
  RASTER_VECTOR_BEST = 'RasterVectorBest',
  VECTOR_BEST = 'VectorBest',
  DTM = 'DTM',
  DSM = 'DSM',
  QUANTIZED_MESH_DTM = 'QuantizedMeshDTM',
  QUANTIZED_MESH_DSM = 'QuantizedMeshDSM',
  QUANTIZED_MESH_DTM_BEST = 'QuantizedMeshDTMBest',
  QUANTIZED_MESH_DSM_BEST = 'QuantizedMeshDSMBest',
  PHOTO_REALISTIC = '3DPhotoRealistic',
  PHOTO_REALISTIC_BEST = '3DPhotoRealisticBest',
  SEMANTIC = '3DSemantic',
  SEMANTIC_MESH = '3DSemanticMesh',
  POINT_CLOUD = '3DPointCloud',
}
